<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) :?>
                <div class="qty-row" data-bind="scope: 'qty-counter'">
                    <button class="qty-button decrement" data-bind="click: decreaseQty">-</button>
                    <div class="field qty">
                        <input type="number"
                               name="qty"
                               id="qty"
                               min="0"
                               value="<?= $block->getProductDefaultQty() * 1 ?>"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                               data-bind="value: qty()"/>
                    </div>
                    <button class="qty-button increment" data-bind="click: increaseQty">+</button>
                </div>
            <?php endif; ?>
            <!--            <div><?php /*= $_product->getQty() */?> Product is in stock</div>
-->
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        },
            "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "qty-counter": {
                        "component": "Magento_Catalog/js/qty-counter",
                        "defaultQty": <?php echo $block->getProductDefaultQty() * 1 ?>
                    }
                }
            }
    }
    }


</script>
