<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
    <div class="box-tocart">
        <div class="fieldset">
            <div class="qty-stock-row">
                <?php if ($block->shouldRenderQuantity()) :?>
                    <div class="qty-row" data-bind="scope: 'qty-counter'">
                        <button class="qty-button decrement" data-bind="click: decreaseQty">-</button>
                        <div class="field qty">
                            <input type="number"
                                   name="qty"
                                   id="qty"
                                   min="0"
                                   value="<?= $block->getProductDefaultQty() * 1 ?>"
                                   title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                                   class="input-text qty"
                                   data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                                   data-bind="value: qty()"/>
                        </div>
                        <button class="qty-button increment" data-bind="click: increaseQty">+</button>
                    </div>
                <?php endif; ?>
                <?php if ($block->displayProductStockStatus()) :?>
                    <?php if ($_product->isAvailable()) :?>
                        <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                            <img src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/in-stock.svg'); ?>"/>
                            <span class="in-stock-normal">
                                <b>IN STOCK </b><?= $_product->getExtensionAttributes()->getStockItem()->getQty() ?> items available
                            </span>
                        </div>
                    <?php else :?>
                        <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>

    </div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        },
            "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "qty-counter": {
                        "component": "Magento_Catalog/js/qty-counter",
                        "defaultQty": <?php echo $block->getProductDefaultQty() * 1 ?>
                    }
                }
            }
    }
    }


</script>
