<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 * @var $viewModel \Magebit\learning\Magento_Catalog\ViewModel\Product\Attributes
 */
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();
$viewModel = $block->getViewModel();

$allAttributes = $block->getAdditionalData();
$validAttributes = $allAttributes ? $viewModel->getSortedAttributes($allAttributes) : [];

?>

<div class="attribute-container">
    <ul class="list">
        <?php foreach ($validAttributes as $attribute): ?>
            <li>
                <b><?= $attribute['label'] ?>:</b>
                <?= $attribute['value']?>
            </li>
        <?php endforeach; ?>
    </ul>
    <div class="short-description"><?= $_product->getShortDescription(); ?></div>
</div>
